[costs]
	#Restored percentage of full durability for an item after repairing with a single valid repair material.
	#Default Value: 0.25
	# Default: 0.25
	# Range: 0.0 ~ 1.0
	repair_with_material_restored_durability = 0.25
	#The additional cost in levels for combining an item with another item of the same kind when the first item is not fully repaired.
	#Default Value: 2
	# Default: 2
	# Range: > 0
	repair_with_other_item_cost = 2
	#Renaming any item in an anvil no longer costs any enchantment levels at all. Can be restricted to only name tags.
	#Default Value: ALL_ITEMS
	#Allowed Values: NEVER, ALL_ITEMS, NAME_TAGS_ONLY
	free_renames = "ALL_ITEMS"
	#Max cost of enchantment level allowed to be spent in an anvil. Every operation exceeding the limit will show as 'Too Expensive!' and will be disallowed.
	#If set to '-1' the limit is disabled.
	#Set to '40' enchantment levels in vanilla.
	#Default Value: -1
	# Default: -1
	# Range: > -1
	too_expensive_limit = -1
	#Percentage of full durability given as a bonus for an item after combining an item with another item of the same kind.
	#Default Value: 0.12
	# Default: 0.12
	# Range: 0.0 ~ 1.0
	repair_with_other_item_bonus_durability = 0.12
	#Costs for applying enchantments from enchanted books are halved.
	#Default Value: true
	halved_book_costs = true
	#The additional cost in levels for each valid repair material an item is repaired with.
	#Default Value: 1
	# Default: 1
	# Range: > 0
	repair_with_material_unit_cost = 1

[prior_work_penalty]
	#FIXED: When renaming / repairing, ignore any prior work penalty on the item. Makes prior work penalty only relevant when new enchantments are added.
	#LIMITED: When renaming / repairing cost exceeds max anvil repair cost, limit cost just below max cost.
	#VANILLA: Renaming / repairing increase with prior work penalty and will no longer be possible when max cost is exceeded.
	#Default Value: FIXED
	#Allowed Values: VANILLA, FIXED, LIMITED
	rename_and_repair_costs = "FIXED"
	#Controls how working an item in the anvil multiple times affects the cost of future operations.
	#LIMITED: Penalty doubles every time an item is worked, but every increase cannot exceed a given limit.
	#VANILLA: Penalty doubles every time an item is worked.
	#NONE: Penalty is disabled by staying at 0 and does not increase.
	#Default Value: LIMITED
	#Allowed Values: NONE, VANILLA, LIMITED
	prior_work_penalty = "LIMITED"
	#Prevents the prior work penalty from increasing when combining two enchanted books.
	#Default Value: true
	penalty_free_enchants_for_books = true
	#Value to use when "prior_work_penalty" is set to "LIMITED". Every subsequent operation will increase at most by this value in levels.
	#Default Value: 4
	# Default: 4
	# Range: > 1
	maximum_prior_work_penalty_increase = 4
	#Prevents the prior work penalty from increasing when the item has only been renamed or repaired.
	#Default Value: true
	penalty_free_renames_and_repairs = true

[miscellaneous]
	#Chance the anvil will break into chipped or damaged variant, or break completely after using. Value is set to 0.12 in vanilla.
	#Default Value: 0.05
	# Default: 0.05
	# Range: 0.0 ~ 1.0
	anvil_break_chance = 0.05
	#Solely renaming items in an anvil will never cause the anvil to break.
	#Default Value: true
	risk_free_anvil_renaming = true
	#Edit name tags without cost nor anvil, simply by sneak + right-clicking.
	#Default Value: true
	edit_name_tags_no_anvil = true
	#The naming field in anvils and the name tag gui will support formatting codes for setting custom text colors and styles.
	#Default Value: true
	renaming_supports_formatting = true
	#Allow using iron blocks to repair an anvil by one damage stage. Can be automated using dispensers.
	#Default Value: true
	anvil_repairing = true
	#Mobs that have a custom name drop a name tag with that name on death.
	#Default Value: false
	name_tags_drop_from_mobs = false
