
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 574291
	#The name of the modpack
	modpackName = "Better MC [FORGE] 1.19.2"
	#The version of the modpack
	modpackVersion = "v20"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

