[Menu]
	#Determines whether the Menu API is enabled or not
	"Enable Menu API" = false
	#Sets the current active menu title screen
	"Active Menu" = "cumulus_menus:minecraft"
	#Adds a button to the top right of the main menu screen to open a menu selection screen
	"Enables menu selection button" = false

["World Preview"]
	#Changes the background panorama into a preview of the latest played world
	"Enables world preview" = false
	#Adds a button to the top right of the main menu screen to toggle between the panorama and world preview
	"Enables toggle world button" = false
	#Adds a button to the top right of the main menu screen to allow quick loading into a world if the world preview is enabled
	"Enables quick load button" = false
