[AerialAffinity]
	#Aerial Affinity is a boots enchantment that increases mining rate when not on the ground.
	"AerialAffinity enabled" = true

[AmethystNoteBlock]
	#Place a block of amethyst under a note block to play its placement sound.
	"AmethystNoteBlock enabled" = true

[ArcanePurpur]
	#Arcane Purpur is a decorative block made from Purpur and Endermite Powder.
	#If the ChorusTeleport feature is enabled, a Chiseled Arcane Purpur block
	#allows teleportation when a chorus fruit is eaten within range of the block.
	"ArcanePurpur enabled" = true

[Atlases]
	#Storage for maps that automatically updates the displayed map as you explore.
	"Atlases enabled" = true
	#Allow opening the atlas while it is in the off-hand.
	"Open in off hand" = false
	#Map scale used in atlases by default.
	"Map scale" = 0

[AutoRecipeUnlock]
	#Unlocks all vanilla recipes.
	#This opinionated feature is disabled by default.
	"AutoRecipeUnlock enabled" = false

[AutoRestock]
	#Refills hotbar from your inventory.
	"AutoRestock enabled" = true

[AzaleaWood]
	#Azalea wood is obtainable from naturally occurring azalea trees or by growing azalea saplings.
	"AzaleaWood enabled" = true

[BatBuckets]
	#Right-click a bat with a bucket to capture it.
	#Right-click again to release it and locate entities around you.
	"BatBuckets enabled" = true

[BeaconsHealMobs]
	#Passive and friendly mobs will heal themselves within range of a beacon with the regeneration effect.
	"BeaconsHealMobs enabled" = true

[Beekeepers]
	#Beekeepers are villagers that trade beekeeping items. Their job site is the beehive.
	"Beekeepers enabled" = true

[CampfiresBoostHealth]
	#Standing within range and sight of a lit campfire provides a small regeneration boost.
	#It does not work if there are enemies nearby.
	"CampfiresBoostHealth enabled" = true

[Chairs]
	#Right-click (with empty hand) on any stairs block to sit down.
	"Chairs enabled" = true

[ChorusTeleport]
	#Eating a chorus fruit within range of a chiseled arcane purpur block teleports the player to the block.
	"ChorusTeleport enabled" = true
	#Range (in blocks) in which a player will be teleported.
	Range = 8

[ClearItemFrames]
	#Add amethyst shards to item frames to make them invisible.
	"ClearItemFrames enabled" = true

[Collection]
	#Tools with the Collection enchantment automatically pick up drops.
	"Collection enabled" = true

[ColoredGlintSmithingTemplates]
	#Smithing template that changes the glint color of any enchanted item.
	"ColoredGlintSmithingTemplates enabled" = true
	#Loot table in which a colored glint smithing template will be added.
	"Loot table" = "minecraft:chests/stronghold_library"
	#Chance (out of 1.0) of a colored glint smithing template appearing in loot.
	"Loot chance" = 1.0

[CopperPistons]
	#Copper Pistons do not have quasi-connectivity.
	"CopperPistons enabled" = true

[CoralSeaLanterns]
	#Coral can be combined with sea lanterns to make colored variants.
	"CoralSeaLanterns enabled" = true

[CoralSquids]
	#Coral Squids spawn near coral in warm oceans.
	"CoralSquids enabled" = true
	#Chance (out of 1.0) of a coral squid dropping coral when killed.
	"Drop chance" = 0.2

[DeepslateDungeons]
	#Dungeons in the deepslate layer will be constructed of deepslate bricks and cobbled deepslate.
	"DeepslateDungeons enabled" = true

[EnchantableHorseArmor]
	#Horse armor can be enchanted.
	"EnchantableHorseArmor enabled" = true
	#Enchantments that will function on horse armor.
	Enchantments = ["minecraft:protection", "minecraft:fire_protection", "minecraft:blast_protection", "minecraft:projectile_protection", "minecraft:thorns", "minecraft:frost_walker", "minecraft:feather_falling", "minecraft:respiration", "minecraft:soul_speed"]

[EndermitePowder]
	#Endermites drop endermite powder that can be used to locate an End City.
	"EndermitePowder enabled" = true

[ExtraMobDrops]
	#Some mobs have a chance to drop additional items.
	"ExtraMobDrops enabled" = true
	#Maximum sand blocks dropped when a husk is killed.
	"Maximum sand drops" = 2
	#Maximum pieces of mutton dropped when a goat is killed.
	"Maximum mutton drops" = 2
	#Maximum cobwebs dropped when a cave spider is killed.
	"Maximum cobweb drops" = 2
	#Chance (out of 1.0) of a witch dropping a Potion of Luck when killed.
	"Luck drop chance" = 0.05
	#Chance (out of 1.0) of a chicken dropping a feather at the same time as an egg.
	"Feather drop chance" = 0.33

[ExtraPortalFrames]
	#Adds more blocks that can be used to build nether portal frames.
	#By default this adds Crying Obsidian.
	"ExtraPortalFrames enabled" = true

[ExtraRecipes]
	#More ways to craft items using different materials.
	"ExtraRecipes enabled" = true
	#If true, adds a blast furnace recipe for smelting raw ore blocks into ore blocks.
	"Ore block from raw ore block" = true
	#If true, adds a recipe for Gilded Blackstone using gold nuggets and blackstone.
	"Gilded Blackstone" = true
	#If true, adds a recipe for Cyan Dye using warped roots.
	"Cyan Dye from warped roots" = true
	#If true, adds a recipe for Green Dye using yellow and blue dyes.
	"Green Dye from yellow and blue" = true
	#If true, adds a recipe for turning snow blocks back into snowballs.
	"Snowballs from snow blocks" = true
	#If true, adds a recipe for turning quartz blocks back into quartz.
	"Quartz from quartz blocks" = true
	#If true, adds a recipe for turning clay blocks back into clay balls.
	"Clay balls from clay blocks" = true
	#If true, adds a recipe for Soul Torches using soul sand/soul soil and sticks.
	"Simpler Soul Torch" = true
	#If true, adds a shapeless recipe for bread.
	"Shapeless bread" = true
	#If true, adds a shapeless recipe for paper.
	"Shapeless paper" = true
	#If true, adds a recipe for TNT using a gunpowder block (if enabled) and any sand.
	"TNT from gunpowder block and sand" = true
	#If true, adds a recipe for crafting bundles from leather.
	"Bundle from leather" = true

[ExtraRepairs]
	#More ways to repair items using different materials.
	"ExtraRepairs enabled" = true
	#Use prismarine shards to repair trident damage.
	"Repair tridents using prismarine" = true
	#Leather can be used to repair elytra when insomnia is disabled.
	"Repair elytra using leather" = true
	#Use netherite scrap to repair netherite item damage.
	"Repair netherite using scrap" = true

[ExtraStackables]
	#Allows some unstackable items to stack.
	"ExtraStackables enabled" = true
	#Enchanted book maximum stack size.
	"Enchanted book" = 1
	#Potion maximum stack size.
	Potion = 1
	#Splash potion maximum stack size.
	"Splash potion" = 1
	#Lingering potion maximum stack size.
	"Lingering potion" = 1
	#Stew (and beetroot soup) maximum stack size.
	Stew = 16
	#Suspicious stew maximum stack size.
	"Suspicious stew" = 1

[ExtraStews]
	#Suspicious stews can be crafted from pitcher plants and sunflowers.
	"ExtraStews enabled" = true
	#Number of seconds of strength and regeneration from a pitcher plant.
	"Pitcher plant effect duration" = 8
	#Number of seconds of health boost from a sunflower.
	"Sunflower effect duration" = 8

[ExtraTrades]
	#Adds more villager trades.
	"ExtraTrades enabled" = true
	#If true, librarians will buy any enchanted book in return for emeralds.
	"Enchanted books" = true
	#If true, armorers, weaponsmiths and toolsmiths will buy chipped or damaged anvils along with iron ingots in return for repaired anvils.
	"Repaired anvils" = true
	#If true, leatherworkers will sell leather in return for rotten flesh.
	"Leather for rotten flesh" = true
	#If true, butchers will sell beef in return for rotten flesh.
	"Beef for rotten flesh" = true
	#If true, leatherworkers will sell bundles in return for emeralds.
	Bundles = true
	#If true, clerics will sell phantom membrane in return for emeralds.
	"Phantom membrane" = true
	#If true, wandering traders have a chance to sell various items from Charm mods.
	"Charm mod items" = true

[ExtractableEnchantments]
	#Extract enchantments from any enchanted item onto an empty book using the grindstone.
	"ExtractableEnchantments enabled" = true
	#Initial cost (in XP levels) of extraction before adding on the cost of the enchantment(s).
	"Initial cost" = 5
	#Adds extra cost (in XP levels) if the enchantment is a treasure enchantment such as Mending.
	"Treasure cost" = 5
	#If true, the item's repair cost will be added to the cost of extraction.
	"Add item repair cost" = true

[GrindableHorseArmor]
	#Horse armor returns a single ingot, leather or diamond when used on the grindstone.
	"GrindableHorseArmor enabled" = true

[HoverSorting]
	#Scroll the mouse while hovering over a bundle or shulker box to cycle the order of its contents.
	"HoverSorting enabled" = true

[ImprovedMineshafts]
	#Adds decoration and more ores to mineshafts.
	"ImprovedMineshafts enabled" = true
	#Chance (out of 1.0) of blocks such as candles and ores spawning on the floor of corridors.
	"Corridor floor blocks" = 0.03
	#Chance (out of 1.0) of blocks such as lanterns spawning on the ceiling of corridors.
	"Corridor ceiling blocks" = 0.02
	#Chance (out of 1.0) of stone, gravel and ore spawning at the entrance of corridors.
	"Corridor block piles" = 0.2
	#Chance (out of 1.0) for a moss or precious ore block to spawn on a single block of the central mineshaft room.
	"Room blocks" = 0.25
	#Chance (out of 1.0) for a minecart to spawn in a corridor. Minecart loot is chosen from the 'Minecart loot tables'.
	"Extra minecarts" = 0.2

[InventoryTidying]
	#Button to automatically tidy inventories.
	"InventoryTidying enabled" = false

[Kilns]
	#A functional block that speeds up cooking of clay, glass, bricks and terracotta.
	"Kilns enabled" = true

[LongerSuspiciousEffects]
	#Beneficial suspicious stew effects last longer.
	"LongerSuspiciousEffects enabled" = true
	#Beneficial suspicious effect duration will be multiplied by this number.
	"Effect multiplier" = 4

[LowerNoteblockPitch]
	#Use a noteblock while sneaking to lower its pitch by one semitone.
	"LowerNoteblockPitch enabled" = true

[Lumberjacks]
	#Lumberjacks are villagers that trade wooden items. Their job site is the woodcutter.
	"Lumberjacks enabled" = true

[MakeSuspiciousBlocks]
	#Use a piston to push an item into sand or gravel, making it suspicious.
	"MakeSuspiciousBlocks enabled" = true

[Mooblooms]
	#Mooblooms are cow-like mobs that come in a variety of flower types.
	#They spawn flowers where they walk and can be milked for suspicious stew.
	"Mooblooms enabled" = true

[NearbyWorkstations]
	#Use workstations such as crafting tables when in range of the block.
	"NearbyWorkstations enabled" = true
	#Range from which player can access a workstation.
	Distance = 16

[NoCropTrampling]
	#Prevents crop trampling when wearing boots enchanted with Feather Falling.
	"NoCropTrampling enabled" = true

[NoPetDamage]
	#Tamed animals do not take direct damage from players.
	"NoPetDamage enabled" = true

[OpenBothDoors]
	#Automatically opens double doors.
	"OpenBothDoors enabled" = true

[ParrotsStayOnShoulder]
	#Parrots stay on player's shoulder when jumping and falling. Crouch to make them dismount.
	"ParrotsStayOnShoulder enabled" = true

[PathConversion]
	#Use a shovel or hoe to convert dirt and path blocks.
	"PathConversion enabled" = true
	#If true, a shovel can be used to convert a dirt block to a path block.
	"Convert dirt to path" = true
	#If true, a hoe can be used to convert a path block to a dirt block.
	"Convert path to dirt" = true

[PiglinsFollowGoldBlocks]
	#Piglins are attracted when the player holds a block of gold.
	"PiglinsFollowGoldBlocks enabled" = true

[PigsFindMushrooms]
	#Pigs have a chance to find mushrooms from mycelium and podzol blocks.
	"PigsFindMushrooms enabled" = true
	#Approximately 1 in X chance of a pig finding a mushroom per game tick.
	"Chance to find mushroom" = 1000
	#Chance (out of 1.0) of a block being converted to dirt when a pig finds a mushroom.
	"Chance to erode block" = 0.25

[PlayerPressurePlates]
	#Player-only pressure plates crafted using smooth basalt.
	"PlayerPressurePlates enabled" = true

[PotionOfRadiance]
	#Potion of Radiance gives the glowing effect. It is brewed using a torchflower.
	"PotionOfRadiance enabled" = true

[QuickReplant]
	#Right-click with a hoe to quickly harvest and replant a fully-grown crop.
	"QuickReplant enabled" = false

[RedstoneSand]
	#A block that acts like sand but is powered like a block of redstone.
	"RedstoneSand enabled" = true

[RevivePets]
	#A named pet drops its name tag on death.
	#Right-click (use) the name tag while holding a Totem of Undying to revive the pet and consume the totem.
	"RevivePets enabled" = true

[ShulkerBoxDragDrop]
	#Drag and drop items into a shulkerbox from within your inventory.
	"ShulkerBoxDragDrop enabled" = true

[SmoothGlowstone]
	#Smooth glowstone.
	"SmoothGlowstone enabled" = true

[SpawnerDrops]
	#Spawners drop mob-related items when broken.
	"SpawnerDrops enabled" = true
	#Spawners only drop items when the game difficulty is set to peaceful.
	"Peaceful only" = true

[StorageBlocks]
	#More item blocks.
	"StorageBlocks enabled" = true
	#If true, ender pearl blocks will be enabled.
	"Ender pearls" = true
	#If true, gunpowder blocks will be enabled.
	Gunpowder = true
	#If true, sugar blocks will be enabled.
	Sugar = true
	#If true, ender pearl blocks will convert silverfish to endermites.
	"Ender pearl block converts silverfish" = true

[StrongerAnvils]
	#Anvils are 50% less likely to take damage when used.
	"StrongerAnvils enabled" = true

[TorchflowersEmitLight]
	#Torchflowers emit ambient light.
	"TorchflowersEmitLight enabled" = true
	#Amount of light emitted by a Torchflower. Valid values between 0-15.
	"Light level" = 8

[TotemOfPreserving]
	#Preserves your items on death.
	"TotemOfPreserving enabled" = false
	#If true, a totem of preserving will always be created when you die.
	#If false, you must be holding a totem of preserving to preserve your items on death.
	"Grave mode" = false
	#The maximum number of times a single totem can be used. Once a totem runs out of uses it is destroyed.
	#A value of -1 means that the totem is never destroyed.
	#You can add an echo shard on an anvil to increase the durability of the totem.
	#Note: Durability has no effect if 'Grave mode' is enabled.
	Durability = 3
	#If true, only the owner of the totem may pick it up.
	"Owner only" = false
	#If true, the coordinates where you died will be added to the player's chat screen.
	"Show death position" = false

[TotemsWorkFromInventory]
	#A totem will work from anywhere in the player's inventory as well as held in the main or offhand.
	#This includes the Totem of Preserving, if enabled.
	"TotemsWorkFromInventory enabled" = true

[UnlimitedRepairCost]
	#Allows anvil repair of items with repair cost 39 or more.
	"UnlimitedRepairCost enabled" = true

[VanillaWoodVariants]
	#Barrels, bookcases, chests and ladders in all vanilla wood types.
	"VanillaWoodVariants enabled" = true

[VillagersFollowEmeraldBlocks]
	#Villagers are attracted when the player holds a block of emeralds.
	"VillagersFollowEmeraldBlocks enabled" = true

[Woodcutters]
	#A functional block that adds more efficient recipes for crafting wooden stairs and slabs.
	"Woodcutters enabled" = true
