[slime]
	#Slime Blobs Enabled
	enabled = true

[charge]
	#Charge Particle Enabled
	enabled = true

[waterCircle]
	#Water Circles Enabled
	enabled = true
	#Water Circles Colored
	colored = true
	#Water Circles Density
	# Default: 16
	# Range: 0 ~ 64
	density = 16
