#Collect partial pick-up entries (when there isn't enough room in your inventory) in the log.
#Might accidentally log items that have not been picked up, therefore it can be disabled.
#Default Value: true
partial_pick_ups = true
#Show entries for items picked up that don't go to the player's inventory. This will enable compatibility with some backpack mods, but might also falsely log items the player never actually receives; depending on the backpack implementation.
backpack_integration = true
