#The title to display at the top of the entry.
title = "Need a server? - Click here!"
#The description to display below the title.
description = "Use CODE: LunaPixel for 25% OFF!"
#Your partner ID to use in during the ordering process.
#Without this you will not be credited for the purchases.
#(Your partner id is not the same as your referral link, please check your client area to find your partner id at https://www.bisecthosting.com/partners/console.php).
partnerId = "2980"
#The id of this modpack.
#(This is BH internal pack id; Find the id here: https://www.bisecthosting.com/partners/console.php)
pack_id = "17037"
#Set this to true to use specific language translation keys.
#This requires a custom mod that adds resource files, such as OpenLoader.
#Use 'server_entry.title' key for the Title;
#Use 'server_entry.description' key for the Description.
use_language_files = false

