# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["########## GL ERROR ##########", "Radium Class Analysis Error: Class org.betterx", "65539: Invalid key -1", "@ Pre render", "@ Render",
"@ Post render", "Disconnecting VANILLA connection attempt", "Attempted to load class net/minecraft/client", 
"UUID of added entity already exists: EntityDragonPart", "Empty or non-existent pool",
"invalid entry \"credits\"", "Ignored non-lowercase namespace", "does not belong to a known attribute. This entry will be ignored", "Detected setBlock in a far chunk"]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX:
	regex = [".*(Unknown block '.*' in '.*' element '.*' at index).*", ".*(GL_INVALID_(OPERATION|VALUE|ENUM)).*"]