#Where to place mods button on main menu screen. Select "NO_CHANGE" to prevent any changes to the screen, useful for mod compatibility.
#Allowed Values: REPLACE_REALMS, LEFT_TO_REALMS, RIGHT_TO_REALMS, INSERT_BELOW_REALMS, NONE, NO_CHANGE
main_menu_mods_button = "INSERT_BELOW_REALMS"
#Add mod count to mods button.
mod_count = true
#Where to place mods button on pause menu screen.
#Allowed Values: REPLACE_FEEDBACK, REPLACE_BUGS, REPLACE_FEEDBACK_AND_BUGS, REPLACE_AND_MOVE_LAN, INSERT_AND_MOVE_LAN, INSERT_BELOW_FEEDBACK_AND_BUGS, NONE
pause_screen_mods_button = "INSERT_BELOW_FEEDBACK_AND_BUGS"
#Show a small green orb indicating that mod updates are available.
update_notification = false
#Safe area in pixels from screen border for buttons to not be moved to prevent them from going off screen.
#Not effective for vanilla menu layouts, but can be useful when mods add buttons close to the border.
#Range: > 0
safe_area = 24

