#Range on xz plane trading post should search for merchants.
#Default Value: 24
# Default: 24
# Range: 1 ~ 96
horizontal_range = 24
#Disable traders on the trading screen when they wander out of range.
#Default Value: false
enforce_range = false
#Teleport xp from trading from villagers on top of the trading post.
#Default Value: true
teleport_xp = true
#Range on y axis trading post should search for merchants.
#Default Value: 16
# Default: 16
# Range: 1 ~ 96
vertical_range = 16
#Close trading post interface when all traders have become unavailable.
#Default Value: true
close_empty_screen = true
